version: '3'

services:
  postgres:
    image: docker.io/library/postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: sked
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bot_net
    container_name: sked_postgres
    restart: always

  sked_bot:
    image: localhost/library/sked_bot:1.0 
    depends_on:
      - postgres
    command: sh -c "/wait && python skedbot/main.py"
    environment:
        - WAIT_HOSTS=postgres:5432
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
        - DATABASE_URL=postgresql://postgres:${PGPASSWORD}@postgres/sked
        - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8000:8000"
    networks:
      - bot_net
    container_name: sked_bot
    volumes:
      - ./creds.json:/creds.json:Z
      - ./token.pickle:/token.pickle:Z
      - /var/log/sked.log:/var/log/sked.log:Z
    restart: always

volumes:
  db:


networks:
  bot_net: {}
